---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv-volume
  namespace: monitoring
  labels:
    type: local
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/prometheus"
