---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom-app
  template:
    metadata:
      labels:
        app: mykubedoom-app
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - image: storaxdev/kubedoom:0.5.0
          name: kubedoom
          ports:
            - containerPort: 5900
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
