---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-deployment
  namespace: kubedoom
  labels:
    app: kubedoom
spec:
  selector:
    matchLabels:
      app: kubedoom
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - name: kubedoom
          image: ghcr.io/storax/kubedoom:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5900
              name: kubedoom
              protocol: TCP
      restartPolicy: Always
