# syntax=docker/dockerfile:1

FROM golang:1.16-alpine as builder

RUN mkdir /build 
ADD . /build/
WORKDIR /build

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .
FROM alpine

COPY --from=builder /build/main /app/
WORKDIR /app

EXPOSE 8080

CMD [ "./main" ]